module.exports = {
    OrganizationError: {
        ORGANIZATION_COMMENT_MONGOOSE_ERROR: 'ORGANIZATION_COMMENT_MONGOOSE_ERROR',
        ORGANIZATION_NOT_FOUND_ERROR: 'ORGANIZATION_NOT_FOUND_ERROR',
        DUPLICATE_ORGANIZATION_COMMENT_ERROR: 'DUPLICATE_ORGANIZATION_COMMENT_ERROR',
        DUPLICATE_ORGANIZATION_ERROR: 'DUPLICATE_ORGANIZATION_ERROR',
        NO_COMMENTS_TO_DELETE_ERROR: 'NO_COMMENTS_TO_DELETE_ERROR'
    }
}
